config/routes.rb
Rails.application.routes.draw do
  # get "/places" => "places#index"
  # get "/places/:id" => "products#show"
  # post "/places" => "places#create"
  # delete "/places:id" => "places#destroy"
  resources :trips
  resources :places
  # get "/apis" => "apis#index"

  # get "/trips" => "trips#index"
  # get "/trips/:id" => "/trips#show"
  # post "/trips" => "trips#create"
  # delete "/trips/:id" => "trips#destroy"

  post "/users" => "users#create"
  post "/sessions" => "sessions#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :places
  accepts_nested_attributes_for :places
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # before_action :set_trip, only: %i[ show edit update destroy ]
  # before_action :authenticate_user

  # GET /trips or /trips.json
  def index
    p current_user
    @trips = Trip.all
    render :index
  end

  # GET /trips/1 or /trips/1.json
  def show
    @trips = Trips.find_by(id: params[:id],user_id: current_user.id)
    render :show
  end

  # GET /trips/new
  # def new
  #   @trip = Trip.new
  # end

  # # GET /trips/1/edit
  # def edit
  # end

  # POST /trips or /trips.json
  def create
    @trip = Trip.new(
      user_id: current_user.id,
      title: params[:title],
      image_url: params[:image_url],
      start_time: params[:start_time],
      end_time: params[:end_time]
    )
    if @trip.save
      
      render json: { message: 'Trip created successfully', trip: @trip }, status: :created
    else
      render json: { error: 'No places provided' }, status: :unprocessable_entity
    end
  end
  


  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip = Trip.find_by(id: params[:id])

    # @trip.status = "removed"
    @trip.destroy
    render json: {message: "Trip was successfully destroyed." }
  end
#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_trip
#       @trip = Trip.find(params[:id])
#     end

    # Only allow a list of trusted parameters through.
end
# require(:trip)
   # Only allow a list of trusted parameters through.
  #  def trip_params
  #   params.permit(:user_id, :title, :image_url, :start_time, :end_time, place_attributes: [:address, :place_id])
  # end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_with(model: trip) do |form| %>
  <% if trip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<div id="<%= dom_id trip %>">
  <p>
    <strong>User:</strong>
    <%= trip.user_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= trip.title %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= trip.image_url %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= trip.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= trip.end_time %>
  </p>

</div>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Show this trip", @trip %> |
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trips</h1>

<div id="trips">
  <% @trips.each do |trip| %>
    <%= render trip %>
    <p>
      <%= link_to "Show this trip", trip %>
    </p>
  <% end %>
</div>

<%= link_to "New trip", new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trip %>

<div>
  <%= link_to "Edit this trip", edit_trip_path(@trip) %> |
  <%= link_to "Back to trips", trips_path %>

  <%= button_to "Destroy this trip", @trip, method: :delete %>
</div>