config/routes.rb
Rails.application.routes.draw do
  # get "/places" => "places#index"
  # get "/places/:id" => "products#show"
  # post "/places" => "places#create"
  # delete "/places:id" => "places#destroy"
  resources :trips
  resources :places
  # get "/apis" => "apis#index"

  # get "/trips" => "trips#index"
  # get "/trips/:id" => "/trips#show"
  # post "/trips" => "trips#create"
  # delete "/trips/:id" => "trips#destroy"

  post "/users" => "users#create"
  post "/sessions" => "sessions#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/place.rb
class Place < ApplicationRecord
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
    render :index
  end

  # GET /places/1 or /places/1.json
  def show
    @place = Place.find_by(id: params[:id])
    render :show
  end

  # GET /places/new
  # def new
  #   @place = Place.new
  # end

  # GET /places/1/edit
  # def edit
  # end

  # POST /places or /places.json
  def create
    @place = Place.new(
      trip_id: params[:trip_id],
      address: params[:address],
      name: params[:name],
      description: params[:description],
      start_time: params[:start_time],
      end_time: params[:end_time]
    )

    if @place.save
      # @image = Image.new(
      #   url: params[:image_url],
      #   place_id: @place.id
      # )
      # @image.save!
      # render :show
      else
        render json: {errors: @place.errors.full_messages}, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
#   def update
#     respond_to do |format|
#       if @place.update(place_params)
#         format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
#         format.json { render :show, status: :ok, location: @place }
#       else
#         format.html { render :edit, status: :unprocessable_entity }
#         format.json { render json: @place.errors, status: :unprocessable_entity }
#       end
#     end
#   end

  # DELETE /places/1 or /places/1.json
  def destroy
    # find the right recipe
    @place = Place.find_by(id: params[:id])
    # delete that recipe
    @place.destroy
    render json: {message: "Place has been successfully removed"}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:trip_id, :address, :name, :description, :image_url, :start_time, :end_time)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
  <% if place.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :trip_id, style: "display: block" %>
    <%= form.number_field :trip_id %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div id="<%= dom_id place %>">
  <p>
    <strong>Trip:</strong>
    <%= place.trip_id %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= place.address %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= place.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= place.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= place.image_url %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= place.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= place.end_time %>
  </p>

</div>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Show this place", @place %> |
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Places</h1>

<div id="places">
  <% @places.each do |place| %>
    <%= render place %>
    <p>
      <%= link_to "Show this place", place %>
    </p>
  <% end %>
</div>

<%= link_to "New place", new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @place %>

<div>
  <%= link_to "Edit this place", edit_place_path(@place) %> |
  <%= link_to "Back to places", places_path %>

  <%= button_to "Destroy this place", @place, method: :delete %>
</div>